// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api/model.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api/model.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathModelSvcHdlModelURL = "/models"

// ModelSvcBMServer is the server API for ModelSvc service.
type ModelSvcBMServer interface {
	HdlModelURL(ctx context.Context, req *GrpcReqs) (resp *GrpcResp, err error)
}

var ModelSvcSvc ModelSvcBMServer

func modelSvcHdlModelURL(c *bm.Context) {
	p := new(GrpcReqs)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ModelSvcSvc.HdlModelURL(c, p)
	c.JSON(resp, err)
}

// RegisterModelSvcBMServer Register the blademaster route
func RegisterModelSvcBMServer(e *bm.Engine, server ModelSvcBMServer) {
	ModelSvcSvc = server
	e.POST("/models", modelSvcHdlModelURL)
}
