
# This is a TOML document. Boom~
appID = "backend.manager.service"
workspace = "/Users/zhaojiachen/Projects/backend-dashboard/backend/workspace"
swaggerFile = "/Users/zhaojiachen/Projects/backend-dashboard/backend/api/api.swagger.json"
