
# This is a TOML document. Boom~
appID = "backend.manager.service"
projPath = "/home/opteacher/projects/backend-dashboard"
workspace = "backend/workspace"
swaggerFile = "backend/api/api.swagger.json"
